# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Retrieve repository contents
        uses: actions/checkout@v3

      - name: Prepare Node.js environment ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Frontend Dependencies
        run: cd tys-webapp && npm install

      - name: Perform Code Formatting Check on Frontend
        run: npm run format-webapp
        
      - name: Perform Linting Check on Frontend
        run: npm run lint-webapp
        
      - name: Install Backend Dependencies
        run: cd tys-apis && npm install
        
      - name: Perform Code Formatting Check on Backend
        run: npm run format-backend
      
      - name: Perform Linting Check on Backend
        run: npm run lint-backend
